name: 🚀 Deploy website

on:
  push:
    paths:
      - "public/"
  workflow_dispatch:

concurrency:
  group: web-deploy
  cancel-in-progress: true

jobs:
  web-deploy:
    runs-on: host
    container:
      image: local-node-lftp:latest

    steps:
      - name: get code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: ftp :3
        run: |
          echo "Starting FTP deployment..."
          lftp -u "$FTP_USER","$FTP_PASSWORD" "$FTP_SERVER" -e 'set ssl:verify-certificate no; mirror -R --delete --verbose public /; quit'
        env:
          FTP_SERVER: ftp.jackpurrin.moe
          FTP_USER: moe@jackpurrin.moe
          FTP_PASSWORD: ${{ secrets.ftp_password }}
